### ISSUE TITLE
Add Actions class

### ISSUE THREAD

**Issue by GoogleCodeExporter** [techtonik/python-patch#13]
```
Actions class will allow customization of python-patch behavior like 
interactive/automatic mode, create/remove files, readonly check if the tree is 
patchable, show patch plan for confirmation by user.
```

Original issue reported on code.google.com by `techtonik@gmail.com` on 27 Sep 2010 at 8:36
* Blocking: #3

**Comment by techtonik** [comment]
One of possible implementations. Not necessarily the best one. Event emitter / handler may be called differently.
