### ISSUE TITLE
Release on Pypi?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [techtonik/python-patch#26]
```
Anatoly: a release on Pypi would be quite nice....
```

Original issue reported on code.google.com by `pombreda...@gmail.com` on 12 Sep 2013 at 3:47

**Comment by techtonik** [comment]
Finally done. https://pypi.python.org/pypi/patch/

**Comment by pombreda** [comment]
@techtonik thank my lord for this!

**Comment by techtonik** [comment]
;)

Sacrifices are accepted at https://gratipay.com/techtonik/
