### ISSUE TITLE
pypi: dead homepage link, thinks 10.04 is latest release

### ISSUE THREAD

**Issue by rofl0r** [techtonik/python-patch#63]
imo you should fix the homepage link on pypi to point here not to google code (404).
also pypi thinks the almost 10 year old 10.04 release is the last released one.

**Comment by pombredanne** [comment]
ping. This is a problem alright!

**Comment by pombredanne** [comment]
@techtonik is this project something you no longer wish to maintain? do you need some help?

**Comment by techtonik** [comment]
Hi ppl. I've just noticed that [Tidelift needs a valid link to GitHub repo](https://blog.tidelift.com/how-to-start-earning-money-for-your-open-source-project-with-tidelift) and remembered I've seen this issue.

The reason I got back to `python-patch` are several CVEs for GNU Patch (#65), so I decided to finally give some love to this utility. I also interested to evaluate if Tidelift and Liberapay can generate any breakfast money. So expect a new release soon.

**Comment by techtonik** [comment]
Removed 10.04 from PyPI. There were no code uploaded, so nothing is lost.

**Comment by techtonik** [comment]
https://pypi.org/project/patch homepage now correctly points to GitHub, but https://libraries.io/pypi/patch did not update. Guess it needs a new release, which is blocked by failing Travis test, that depend on `pypack` experiencing problems with Python 3.4.8 - https://travis-ci.org/techtonik/python-patch/jobs/577891157#L212 It was ok with Python 3.4.2 so I need more time to look into that.

**Comment by pombredanne** [comment]
My 2 cents: drop support for Python 3.4

**Comment by techtonik** [comment]
Something was changed and now 3.5+ doesn't work with the same error.

**Comment by techtonik** [comment]
Adding CI to https://github.com/techtonik/pypack - looks like Python 3 compatibility was broken right after pypack 0.1 (last 0.2 and 0.3 version don't work).

**Comment by rofl0r** [comment]
i'm very much in favor of keeping py2 support myself. my distro sabotage linux uses only py2 things by default (basically anything that uses python for building, works with py2, so thankfully we don't need to have 2 different py versions installed to bootstrap the system from source). also i pretty much enjoy python2 being a "completed" language,
i.e. nothing changes and the language isn't constantly redesigned behind my back.

anyway, thanks for updating the links!

**Comment by techtonik** [comment]
`libraries.io` still was not updated this morning, so resynced the project manually - https://github.com/librariesio/libraries.io/issues/2420#issuecomment-526805311

Homepage is now Ok everythere, 10.04 is gone. Yay! =)
